#!/bin/sh
# gen-version.sh -- resolve the hafod version and emit the version library.
#
# Source of truth: git tags (e.g. `git tag v1.5.1`). Falls back to the tracked
# ./VERSION file for builds without a .git (release tarballs, nix `github:`
# sources), then to a dev placeholder. This keeps the version in exactly one
# place -- the tag -- with no per-release edits to source files.
#
# Usage:
#   tools/gen-version.sh           Write src/hafod/internal/version.ss (if changed).
#   tools/gen-version.sh --print   Print the resolved version string and exit.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

resolve_version() {
  # Strip the leading "v" from tags like v1.5.1. `git describe` yields the
  # exact tag on a release commit, or "1.5.1-3-gabc123" when ahead of it.
  v=$(git -C "$root" describe --tags 2>/dev/null | sed 's/^v//') || v=
  [ -n "$v" ] || v=$(cat "$root/VERSION" 2>/dev/null || true)
  [ -n "$v" ] || v=0.0.0-dev
  printf '%s' "$v"
}

ver=$(resolve_version)

if [ "${1:-}" = "--print" ]; then
  printf '%s\n' "$ver"
  exit 0
fi

# Parse leading major/minor for the scsh-compatible numeric constants.
major=$(printf '%s' "$ver" | sed -n 's/^\([0-9][0-9]*\).*/\1/p'); [ -n "$major" ] || major=0
minor=$(printf '%s' "$ver" | sed -n 's/^[0-9][0-9]*\.\([0-9][0-9]*\).*/\1/p'); [ -n "$minor" ] || minor=0

out="$root/src/hafod/internal/version.ss"
tmp="$out.tmp.$$"
cat > "$tmp" <<EOF
;;; (hafod internal version) -- Auto-generated, do not edit.
;;; Source of truth: git tags. Regenerated by tools/gen-version.sh on build.
(library (hafod internal version)
  (export hafod-version hafod-version-major hafod-version-minor)
  (import (chezscheme))
  (define hafod-version "$ver")
  (define hafod-version-major $major)
  (define hafod-version-minor $minor))
EOF

# Only replace when the content changes, so incremental builds don't needlessly
# recompile the libraries that depend on the version module.
if [ ! -f "$out" ] || ! cmp -s "$tmp" "$out"; then
  mv "$tmp" "$out"
  echo "gen-version: $ver"
else
  rm -f "$tmp"
fi
