/* gen-platform-constants.c -- Generate platform-specific struct offsets and constants
 *
 * Compiles and runs on the target platform to produce a Scheme library
 * (hafod internal platform-constants) with correct struct layouts,
 * signal numbers, and flag values for the current OS/architecture.
 *
 * Usage:
 *   cc -o tools/gen-platform-constants tools/gen-platform-constants.c
 *   tools/gen-platform-constants > src/hafod/internal/platform-constants.ss
 */

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <limits.h>
#include <stddef.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <dirent.h>
#include <termios.h>
#include <time.h>
#include <sys/times.h>
#include <regex.h>
#include <glob.h>
#include <fnmatch.h>
#include <fcntl.h>
#include <pwd.h>
#include <grp.h>
#include <spawn.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/utsname.h>
#include <locale.h>

/* Width-correct emission with a self-proving round-trip.
 *
 * Every numeric platform fact is emitted as a decimal literal and then
 * re-parsed from that very literal; if the parse-back does not equal the
 * native C value the generator aborts (non-zero exit), naming the constant,
 * so a lossy transcription fails the build before any Scheme compiles.
 *
 * Two families differ in conversion AND in the parse-back used to prove it:
 *   EMIT_S -- signed   (%ld / strtol):  offsets, sizes, signal numbers,
 *                                        cc indices, action enums, -1 sentinels.
 *   EMIT_U -- unsigned (%lu / strtoul): ioctl requests and flag/bitmask values
 *                                        where a high bit may be set (emitting
 *                                        these signed would sign-extend in Chez).
 *
 * A -1 sentinel must never go through EMIT_U: strtoul would wrap it to
 * ULONG_MAX. Sentinels stay on EMIT_S.
 */
static void die_mismatch(const char *name, long long want, long long got) {
    fprintf(stderr,
        "gen-platform-constants: TRUNCATION/ROUND-TRIP FAILURE for %s: "
        "native=%lld emitted-decimal-parsed-back=%lld\n", name, want, got);
    exit(1);                       /* non-zero -> fails `make platform-constants` */
}

/* SIGNED category: offsets, sizes, signal numbers, sentinels (-1 allowed). */
#define EMIT_S(name, val) do {                                            \
    long _v = (long)(val);                                                \
    printf("  (define %s %ld)\n", name, _v);                              \
    char _buf[32]; snprintf(_buf, sizeof _buf, "%ld", _v);                \
    errno = 0; char *_end = NULL;                                         \
    long _rt = strtol(_buf, &_end, 10);                                   \
    if (errno || *_end != '\0' || _rt != _v) die_mismatch(name, _v, _rt);\
} while (0)

/* UNSIGNED category: ioctl requests, flag masks (bit 31 may be set). */
#define EMIT_U(name, val) do {                                            \
    unsigned long _v = (unsigned long)(val);                              \
    printf("  (define %s %lu)\n", name, _v);                              \
    char _buf[32]; snprintf(_buf, sizeof _buf, "%lu", _v);                \
    errno = 0; char *_end = NULL;                                         \
    unsigned long _rt = strtoul(_buf, &_end, 10);                         \
    if (errno || *_end != '\0' || _rt != _v)                             \
        die_mismatch(name, (long long)_v, (long long)_rt);                \
} while (0)

/* Offsets and sizes are nonnegative and small: thin wrappers over EMIT_S. */
#define EMIT_OFFSET(name, type, field) \
    EMIT_S(name, (long)offsetof(type, field))
#define EMIT_SIZEOF(name, type) \
    EMIT_S(name, (long)sizeof(type))
#define EMIT_FIELD_SIZEOF(name, type, field) \
    EMIT_S(name, (long)sizeof(((type *)0)->field))

int main(void) {
    printf(";;; (hafod internal platform-constants) -- Auto-generated, do not edit\n");
    printf(";;; Generated by tools/gen-platform-constants.c for this platform.\n");
    printf("\n");
    printf("(library (hafod internal platform-constants)\n");
    printf("  (export\n");

    /* struct stat */
    printf("    SIZEOF-STAT\n");
    printf("    STAT-ST-DEV STAT-ST-INO STAT-ST-NLINK STAT-ST-MODE\n");
    printf("    STAT-ST-UID STAT-ST-GID STAT-ST-RDEV STAT-ST-SIZE\n");
    printf("    STAT-ST-BLKSIZE STAT-ST-BLOCKS STAT-ST-ATIM STAT-ST-MTIM STAT-ST-CTIM\n");
    printf("    SIZEOF-ST-DEV SIZEOF-ST-INO SIZEOF-ST-NLINK SIZEOF-ST-MODE\n");
    printf("    SIZEOF-ST-RDEV SIZEOF-ST-BLKSIZE SIZEOF-ST-BLOCKS\n");

    /* struct dirent */
    printf("    DIRENT-D-INO DIRENT-D-OFF DIRENT-D-RECLEN DIRENT-D-TYPE DIRENT-D-NAME\n");

    /* struct passwd */
    printf("    PW-NAME PW-PASSWD PW-UID PW-GID PW-GECOS PW-DIR PW-SHELL\n");

    /* struct group */
    printf("    GR-NAME GR-PASSWD GR-GID GR-MEM\n");

    /* struct termios */
    printf("    SIZEOF-TERMIOS\n");
    printf("    TERMIOS-C-IFLAG TERMIOS-C-OFLAG TERMIOS-C-CFLAG TERMIOS-C-LFLAG\n");
    printf("    TERMIOS-C-CC TERMIOS-C-ISPEED TERMIOS-C-OSPEED\n");

    /* struct tm */
    printf("    SIZEOF-TM\n");
    printf("    TM-SEC TM-MIN TM-HOUR TM-MDAY TM-MON TM-YEAR\n");
    printf("    TM-WDAY TM-YDAY TM-ISDST TM-GMTOFF TM-ZONE\n");

    /* struct tms */
    printf("    SIZEOF-TMS\n");

    /* regex_t and regmatch_t */
    printf("    SIZEOF-REGEX-T SIZEOF-REGMATCH-T SIZEOF-REGOFF-T\n");

    /* glob_t */
    printf("    SIZEOF-GLOB-T GLOB-GL-PATHC GLOB-GL-PATHV\n");

    /* posix_spawn_file_actions_t */
    printf("    SIZEOF-SPAWN-FA\n");

    /* Open flags */
    printf("    PLAT-O-CREAT PLAT-O-EXCL PLAT-O-TRUNC PLAT-O-APPEND PLAT-O-NONBLOCK\n");

    /* Signals that vary across platforms */
    printf("    PLAT-SIGBUS PLAT-SIGUSR1 PLAT-SIGUSR2 PLAT-SIGCHLD\n");
    printf("    PLAT-SIGCONT PLAT-SIGSTOP PLAT-SIGTSTP PLAT-SIGTTIN PLAT-SIGTTOU\n");
    printf("    PLAT-SIGURG PLAT-SIGXCPU PLAT-SIGXFSZ PLAT-SIGVTALRM\n");
    printf("    PLAT-SIGPROF PLAT-SIGWINCH PLAT-SIGIO PLAT-SIGSYS\n");
    printf("    PLAT-SIGPWR PLAT-SIGINFO\n");

    /* errno constants */
    printf("    PLAT-EINTR\n");

    /* TTY flag values */
    printf("    PLAT-IGNBRK PLAT-BRKINT PLAT-IGNPAR PLAT-PARMRK\n");
    printf("    PLAT-INPCK PLAT-ISTRIP PLAT-INLCR PLAT-IGNCR PLAT-ICRNL\n");
    printf("    PLAT-IXON PLAT-IXOFF PLAT-IXANY\n");
    printf("    PLAT-OPOST PLAT-ONLCR\n");
    printf("    PLAT-CSIZE PLAT-CS5 PLAT-CS6 PLAT-CS7 PLAT-CS8\n");
    printf("    PLAT-CSTOPB PLAT-CREAD PLAT-PARENB PLAT-PARODD\n");
    printf("    PLAT-HUPCL PLAT-CLOCAL\n");
    printf("    PLAT-ISIG PLAT-ICANON PLAT-ECHO PLAT-ECHOE PLAT-ECHOK\n");
    printf("    PLAT-ECHONL PLAT-NOFLSH PLAT-TOSTOP PLAT-IEXTEN\n");

    /* TTY cc indices */
    printf("    PLAT-VINTR PLAT-VQUIT PLAT-VERASE PLAT-VKILL PLAT-VEOF\n");
    printf("    PLAT-VTIME PLAT-VMIN PLAT-VSTART PLAT-VSTOP PLAT-VSUSP\n");
    printf("    PLAT-VEOL PLAT-VREPRINT PLAT-VDISCARD PLAT-VWERASE PLAT-VLNEXT PLAT-VEOL2\n");
    printf("    PLAT-NCCS\n");

    /* termios actions */
    printf("    PLAT-TCSANOW PLAT-TCSADRAIN PLAT-TCSAFLUSH\n");
    printf("    PLAT-TCIFLUSH PLAT-TCOFLUSH PLAT-TCIOFLUSH\n");
    printf("    PLAT-TCOOFF PLAT-TCOON PLAT-TCIOFF PLAT-TCION\n");

    /* fcntl */
    printf("    PLAT-F-GETFD PLAT-F-SETFD PLAT-FD-CLOEXEC PLAT-F-GETFL PLAT-F-SETFL\n");

    /* ioctl */
    printf("    PLAT-TIOCSCTTY\n");
    printf("    PLAT-TIOCGWINSZ\n");

    /* struct winsize layout */
    printf("    SIZEOF-WINSZ WINSZ-WS-ROW WINSZ-WS-COL\n");

    /* utsname */
    printf("    PLAT-UTSNAME-FIELD-LEN\n");

    /* O_NOCTTY */
    printf("    PLAT-O-NOCTTY\n");

    /* FNM flags */
    printf("    PLAT-FNM-NOESCAPE PLAT-FNM-PATHNAME PLAT-FNM-PERIOD\n");

    /* Regex flags */
    printf("    PLAT-REG-EXTENDED PLAT-REG-ICASE PLAT-REG-NOSUB PLAT-REG-NEWLINE\n");
    printf("    PLAT-REG-NOTBOL PLAT-REG-NOTEOL PLAT-REG-NOMATCH PLAT-REG-STARTEND\n");

    /* Locale */
    printf("    PLAT-LC-ALL PLAT-LC-COLLATE\n");

    printf("  )\n");
    printf("  (import (chezscheme))\n\n");

    /* ============================================================ */
    printf("  ;; struct stat\n");
    EMIT_SIZEOF("SIZEOF-STAT", struct stat);
    EMIT_OFFSET("STAT-ST-DEV", struct stat, st_dev);
    EMIT_OFFSET("STAT-ST-INO", struct stat, st_ino);
    EMIT_OFFSET("STAT-ST-NLINK", struct stat, st_nlink);
    EMIT_OFFSET("STAT-ST-MODE", struct stat, st_mode);
    EMIT_OFFSET("STAT-ST-UID", struct stat, st_uid);
    EMIT_OFFSET("STAT-ST-GID", struct stat, st_gid);
    EMIT_OFFSET("STAT-ST-RDEV", struct stat, st_rdev);
    EMIT_OFFSET("STAT-ST-SIZE", struct stat, st_size);
    EMIT_OFFSET("STAT-ST-BLKSIZE", struct stat, st_blksize);
    EMIT_OFFSET("STAT-ST-BLOCKS", struct stat, st_blocks);
    /* st_atim is a struct timespec; macOS uses st_atimespec instead */
#ifdef __APPLE__
    EMIT_OFFSET("STAT-ST-ATIM", struct stat, st_atimespec);
    EMIT_OFFSET("STAT-ST-MTIM", struct stat, st_mtimespec);
    EMIT_OFFSET("STAT-ST-CTIM", struct stat, st_ctimespec);
#else
    EMIT_OFFSET("STAT-ST-ATIM", struct stat, st_atim);
    EMIT_OFFSET("STAT-ST-MTIM", struct stat, st_mtim);
    EMIT_OFFSET("STAT-ST-CTIM", struct stat, st_ctim);
#endif
    EMIT_FIELD_SIZEOF("SIZEOF-ST-DEV", struct stat, st_dev);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-INO", struct stat, st_ino);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-NLINK", struct stat, st_nlink);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-MODE", struct stat, st_mode);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-RDEV", struct stat, st_rdev);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-BLKSIZE", struct stat, st_blksize);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-BLOCKS", struct stat, st_blocks);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct dirent\n");
    EMIT_OFFSET("DIRENT-D-INO", struct dirent, d_ino);
#ifdef __linux__
    EMIT_OFFSET("DIRENT-D-OFF", struct dirent, d_off);
#else
    /* macOS/BSD don't have d_off in struct dirent */
    EMIT_S("DIRENT-D-OFF", -1);
#endif
    EMIT_OFFSET("DIRENT-D-RECLEN", struct dirent, d_reclen);
    EMIT_OFFSET("DIRENT-D-TYPE", struct dirent, d_type);
    EMIT_OFFSET("DIRENT-D-NAME", struct dirent, d_name);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct passwd\n");
    EMIT_OFFSET("PW-NAME", struct passwd, pw_name);
    EMIT_OFFSET("PW-PASSWD", struct passwd, pw_passwd);
    EMIT_OFFSET("PW-UID", struct passwd, pw_uid);
    EMIT_OFFSET("PW-GID", struct passwd, pw_gid);
    EMIT_OFFSET("PW-GECOS", struct passwd, pw_gecos);
    EMIT_OFFSET("PW-DIR", struct passwd, pw_dir);
    EMIT_OFFSET("PW-SHELL", struct passwd, pw_shell);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct group\n");
    EMIT_OFFSET("GR-NAME", struct group, gr_name);
    EMIT_OFFSET("GR-PASSWD", struct group, gr_passwd);
    EMIT_OFFSET("GR-GID", struct group, gr_gid);
    EMIT_OFFSET("GR-MEM", struct group, gr_mem);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct termios\n");
    EMIT_SIZEOF("SIZEOF-TERMIOS", struct termios);
    EMIT_OFFSET("TERMIOS-C-IFLAG", struct termios, c_iflag);
    EMIT_OFFSET("TERMIOS-C-OFLAG", struct termios, c_oflag);
    EMIT_OFFSET("TERMIOS-C-CFLAG", struct termios, c_cflag);
    EMIT_OFFSET("TERMIOS-C-LFLAG", struct termios, c_lflag);
    EMIT_OFFSET("TERMIOS-C-CC", struct termios, c_cc);
    EMIT_OFFSET("TERMIOS-C-ISPEED", struct termios, c_ispeed);
    EMIT_OFFSET("TERMIOS-C-OSPEED", struct termios, c_ospeed);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct tm\n");
    EMIT_SIZEOF("SIZEOF-TM", struct tm);
    EMIT_OFFSET("TM-SEC", struct tm, tm_sec);
    EMIT_OFFSET("TM-MIN", struct tm, tm_min);
    EMIT_OFFSET("TM-HOUR", struct tm, tm_hour);
    EMIT_OFFSET("TM-MDAY", struct tm, tm_mday);
    EMIT_OFFSET("TM-MON", struct tm, tm_mon);
    EMIT_OFFSET("TM-YEAR", struct tm, tm_year);
    EMIT_OFFSET("TM-WDAY", struct tm, tm_wday);
    EMIT_OFFSET("TM-YDAY", struct tm, tm_yday);
    EMIT_OFFSET("TM-ISDST", struct tm, tm_isdst);
    EMIT_OFFSET("TM-GMTOFF", struct tm, tm_gmtoff);
    EMIT_OFFSET("TM-ZONE", struct tm, tm_zone);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct tms\n");
    EMIT_SIZEOF("SIZEOF-TMS", struct tms);
    printf("\n");

    /* ============================================================ */
    printf("  ;; regex_t and regmatch_t\n");
    EMIT_SIZEOF("SIZEOF-REGEX-T", regex_t);
    EMIT_SIZEOF("SIZEOF-REGMATCH-T", regmatch_t);
    EMIT_SIZEOF("SIZEOF-REGOFF-T", regoff_t);
    printf("\n");

    /* ============================================================ */
    printf("  ;; glob_t\n");
    EMIT_SIZEOF("SIZEOF-GLOB-T", glob_t);
    EMIT_OFFSET("GLOB-GL-PATHC", glob_t, gl_pathc);
    EMIT_OFFSET("GLOB-GL-PATHV", glob_t, gl_pathv);
    printf("\n");

    /* ============================================================ */
    printf("  ;; posix_spawn_file_actions_t\n");
    EMIT_SIZEOF("SIZEOF-SPAWN-FA", posix_spawn_file_actions_t);
    printf("\n");

    /* ============================================================ */
    printf("  ;; Open flags\n");
    EMIT_U("PLAT-O-CREAT", O_CREAT);
    EMIT_U("PLAT-O-EXCL", O_EXCL);
    EMIT_U("PLAT-O-TRUNC", O_TRUNC);
    EMIT_U("PLAT-O-APPEND", O_APPEND);
    EMIT_U("PLAT-O-NONBLOCK", O_NONBLOCK);
    printf("\n");

    /* ============================================================ */
    printf("  ;; Signal constants\n");
    EMIT_S("PLAT-SIGBUS", SIGBUS);
    EMIT_S("PLAT-SIGUSR1", SIGUSR1);
    EMIT_S("PLAT-SIGUSR2", SIGUSR2);
    EMIT_S("PLAT-SIGCHLD", SIGCHLD);
    EMIT_S("PLAT-SIGCONT", SIGCONT);
    EMIT_S("PLAT-SIGSTOP", SIGSTOP);
    EMIT_S("PLAT-SIGTSTP", SIGTSTP);
    EMIT_S("PLAT-SIGTTIN", SIGTTIN);
    EMIT_S("PLAT-SIGTTOU", SIGTTOU);
    EMIT_S("PLAT-SIGURG", SIGURG);
    EMIT_S("PLAT-SIGXCPU", SIGXCPU);
    EMIT_S("PLAT-SIGXFSZ", SIGXFSZ);
    EMIT_S("PLAT-SIGVTALRM", SIGVTALRM);
    EMIT_S("PLAT-SIGPROF", SIGPROF);
    EMIT_S("PLAT-SIGWINCH", SIGWINCH);
    EMIT_S("PLAT-SIGIO", SIGIO);
    EMIT_S("PLAT-SIGSYS", SIGSYS);
    printf("\n");

    /* ============================================================ */
    printf("  ;; platform-varying signals (sentinel -1 where unavailable)\n");
#ifdef SIGPWR
    EMIT_S("PLAT-SIGPWR", SIGPWR);     /* Linux: 30 */
#else
    EMIT_S("PLAT-SIGPWR", -1);         /* macOS/BSD: absent */
#endif
#ifdef SIGINFO
    EMIT_S("PLAT-SIGINFO", SIGINFO);   /* BSD/macOS: present */
#else
    EMIT_S("PLAT-SIGINFO", -1);        /* Linux glibc: absent */
#endif
    printf("\n");

    /* ============================================================ */
    /* EINTR is a small positive signed int, universal on Linux/macOS/BSD --
       no #ifdef needed. It rides the signed EMIT_S path like a signal number. */
    printf("  ;; errno constants\n");
    EMIT_S("PLAT-EINTR", EINTR);
    printf("\n");

    /* ============================================================ */
    printf("  ;; TTY input flags\n");
    EMIT_U("PLAT-IGNBRK", IGNBRK);
    EMIT_U("PLAT-BRKINT", BRKINT);
    EMIT_U("PLAT-IGNPAR", IGNPAR);
    EMIT_U("PLAT-PARMRK", PARMRK);
    EMIT_U("PLAT-INPCK", INPCK);
    EMIT_U("PLAT-ISTRIP", ISTRIP);
    EMIT_U("PLAT-INLCR", INLCR);
    EMIT_U("PLAT-IGNCR", IGNCR);
    EMIT_U("PLAT-ICRNL", ICRNL);
    EMIT_U("PLAT-IXON", IXON);
    EMIT_U("PLAT-IXOFF", IXOFF);
    EMIT_U("PLAT-IXANY", IXANY);
    printf("\n");

    printf("  ;; TTY output flags\n");
    EMIT_U("PLAT-OPOST", OPOST);
    EMIT_U("PLAT-ONLCR", ONLCR);
    printf("\n");

    printf("  ;; TTY control flags\n");
    EMIT_U("PLAT-CSIZE", CSIZE);
    EMIT_U("PLAT-CS5", CS5);
    EMIT_U("PLAT-CS6", CS6);
    EMIT_U("PLAT-CS7", CS7);
    EMIT_U("PLAT-CS8", CS8);
    EMIT_U("PLAT-CSTOPB", CSTOPB);
    EMIT_U("PLAT-CREAD", CREAD);
    EMIT_U("PLAT-PARENB", PARENB);
    EMIT_U("PLAT-PARODD", PARODD);
    EMIT_U("PLAT-HUPCL", HUPCL);
    EMIT_U("PLAT-CLOCAL", CLOCAL);
    printf("\n");

    printf("  ;; TTY local flags\n");
    EMIT_U("PLAT-ISIG", ISIG);
    EMIT_U("PLAT-ICANON", ICANON);
    EMIT_U("PLAT-ECHO", ECHO);
    EMIT_U("PLAT-ECHOE", ECHOE);
    EMIT_U("PLAT-ECHOK", ECHOK);
    EMIT_U("PLAT-ECHONL", ECHONL);
    EMIT_U("PLAT-NOFLSH", NOFLSH);
    EMIT_U("PLAT-TOSTOP", TOSTOP);
    EMIT_U("PLAT-IEXTEN", IEXTEN);
    printf("\n");

    printf("  ;; TTY cc indices\n");
    EMIT_S("PLAT-VINTR", VINTR);
    EMIT_S("PLAT-VQUIT", VQUIT);
    EMIT_S("PLAT-VERASE", VERASE);
    EMIT_S("PLAT-VKILL", VKILL);
    EMIT_S("PLAT-VEOF", VEOF);
    EMIT_S("PLAT-VTIME", VTIME);
    EMIT_S("PLAT-VMIN", VMIN);
    EMIT_S("PLAT-VSTART", VSTART);
    EMIT_S("PLAT-VSTOP", VSTOP);
    EMIT_S("PLAT-VSUSP", VSUSP);
    EMIT_S("PLAT-VEOL", VEOL);
    EMIT_S("PLAT-VREPRINT", VREPRINT);
    EMIT_S("PLAT-VDISCARD", VDISCARD);
    EMIT_S("PLAT-VWERASE", VWERASE);
    EMIT_S("PLAT-VLNEXT", VLNEXT);
    EMIT_S("PLAT-VEOL2", VEOL2);
    EMIT_S("PLAT-NCCS", NCCS);
    printf("\n");

    printf("  ;; termios actions\n");
    EMIT_S("PLAT-TCSANOW", TCSANOW);
    EMIT_S("PLAT-TCSADRAIN", TCSADRAIN);
    EMIT_S("PLAT-TCSAFLUSH", TCSAFLUSH);
    EMIT_S("PLAT-TCIFLUSH", TCIFLUSH);
    EMIT_S("PLAT-TCOFLUSH", TCOFLUSH);
    EMIT_S("PLAT-TCIOFLUSH", TCIOFLUSH);
    EMIT_S("PLAT-TCOOFF", TCOOFF);
    EMIT_S("PLAT-TCOON", TCOON);
    EMIT_S("PLAT-TCIOFF", TCIOFF);
    EMIT_S("PLAT-TCION", TCION);
    printf("\n");

    printf("  ;; fcntl\n");
    EMIT_S("PLAT-F-GETFD", F_GETFD);
    EMIT_S("PLAT-F-SETFD", F_SETFD);
    EMIT_S("PLAT-FD-CLOEXEC", FD_CLOEXEC);
    EMIT_S("PLAT-F-GETFL", F_GETFL);
    EMIT_S("PLAT-F-SETFL", F_SETFL);
    printf("\n");

    printf("  ;; ioctl\n");
    EMIT_U("PLAT-TIOCSCTTY", TIOCSCTTY);
    EMIT_U("PLAT-TIOCGWINSZ", TIOCGWINSZ);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct winsize\n");
    EMIT_SIZEOF("SIZEOF-WINSZ", struct winsize);
    EMIT_OFFSET("WINSZ-WS-ROW", struct winsize, ws_row);
    EMIT_OFFSET("WINSZ-WS-COL", struct winsize, ws_col);
    printf("\n");

    printf("  ;; utsname\n");
    {
        struct utsname u;
        EMIT_S("PLAT-UTSNAME-FIELD-LEN", sizeof(u.sysname));
    }
    printf("\n");

    printf("  ;; O_NOCTTY\n");
    EMIT_U("PLAT-O-NOCTTY", O_NOCTTY);
    printf("\n");

    printf("  ;; fnmatch flags\n");
    /* Use the real <fnmatch.h> macros: glibc and the BSDs/macOS disagree --
       glibc has FNM_PATHNAME=1, FNM_NOESCAPE=2 whereas the BSDs use
       FNM_NOESCAPE=1, FNM_PATHNAME=2 -- so a hardcoded literal is wrong on
       one of them. */
    EMIT_U("PLAT-FNM-NOESCAPE", FNM_NOESCAPE);
    EMIT_U("PLAT-FNM-PATHNAME", FNM_PATHNAME);
    EMIT_U("PLAT-FNM-PERIOD", FNM_PERIOD);
    printf("\n");

    printf("  ;; Regex flags\n");
    EMIT_U("PLAT-REG-EXTENDED", REG_EXTENDED);
    EMIT_U("PLAT-REG-ICASE", REG_ICASE);
    EMIT_U("PLAT-REG-NOSUB", REG_NOSUB);
    EMIT_U("PLAT-REG-NEWLINE", REG_NEWLINE);
    EMIT_U("PLAT-REG-NOTBOL", REG_NOTBOL);
    EMIT_U("PLAT-REG-NOTEOL", REG_NOTEOL);
    EMIT_U("PLAT-REG-NOMATCH", REG_NOMATCH);
    EMIT_U("PLAT-REG-STARTEND", REG_STARTEND);

    printf("  ;; Locale\n");
    EMIT_S("PLAT-LC-ALL", LC_ALL);
    EMIT_S("PLAT-LC-COLLATE", LC_COLLATE);
    printf("\n");

    printf("\n) ; end library\n");
    return 0;
}
