#!/bin/sh
# gen-chez-version.sh -- record the build Chez version and emit the recorded
# version library.
#
# Source of truth: the Chez interpreter used for the build. The build Chez
# reports its own (scheme-version-number) triple, which is written into
# src/hafod/internal/chez-version.ss. The launcher's version guard reads this
# recorded triple to detect a runtime Chez that does not match the one the
# compiled libraries were built with.
#
# This is a sibling of gen-version.sh rather than an extension of it: keeping
# the Chez invocation here leaves gen-version.sh entirely Scheme-free, so its
# --print path stays usable for the man page without spawning an interpreter.
#
# Usage:
#   SCHEME=scheme tools/gen-chez-version.sh   Write the recorded version
#                                             library (only if it changed).
#
# $SCHEME is supplied by the Makefile; it defaults to "scheme" so a bare
# invocation still works.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

: "${SCHEME:=scheme}"

# Ask the build Chez for its own version triple. (scheme-version-number)
# returns THREE VALUES (major, minor, sub-minor), not a list, so it must be
# consumed with call-with-values and a three-argument lambda -- treating it as
# a single value raises "returned 3 values to single value return context".
# The result is captured as a space-separated "major minor sub" string.
triple="$("$SCHEME" -q <<'EOF'
(call-with-values (lambda () (scheme-version-number))
  (lambda (a b c) (display a)(display " ")(display b)(display " ")(display c)))
EOF
)"

# Validate before writing anything. A real Chez prints exactly three
# space-separated integers. If $SCHEME is not Chez but happens to exit 0 and
# ignore stdin (e.g. a typo resolving to another tool), it can emit junk on
# stdout, set -e does not trip, and an unvalidated splice would record a bogus
# "version" like (-q) -- which silently disables the launcher's version guard
# (its sed needs three integers, so it yields empty and the check is skipped),
# the exact opposite of this script's purpose. Refuse loudly instead.
case "$triple" in
  [0-9]*' '[0-9]*' '[0-9]*) : ;;   # three space-separated integers
  *)
    echo "gen-chez-version: '$SCHEME' did not report a Chez version triple (got: '$triple')" >&2
    exit 1 ;;
esac

out="$root/src/hafod/internal/chez-version.ss"
tmp="$out.tmp.$$"
cat > "$tmp" <<EOF
;;; (hafod internal chez-version) -- Auto-generated, do not edit.
;;; Records the build Chez (scheme-version-number) triple. Source of truth for
;;; the launcher version guard. Regenerated by tools/gen-chez-version.sh on build.
(library (hafod internal chez-version)
  (export build-chez-version-number)
  (import (chezscheme))
  (define build-chez-version-number '($triple)))
EOF

# Only replace when the content changes, so a rebuild under the same Chez does
# not rewrite the file. This keeps incremental builds quiet and, since the
# launcher artefact depends on this module's sources, keeps its mtime graph
# stable. A build under a different Chez yields a different triple and so does
# rewrite the module.
if [ ! -f "$out" ] || ! cmp -s "$tmp" "$out"; then
  mv "$tmp" "$out"
  echo "gen-chez-version: $triple"
else
  rm -f "$tmp"
fi
