/* gen-platform-constants.c -- Generate platform-specific struct offsets and constants
 *
 * Compiles and runs on the target platform to produce a Scheme library
 * (hafod internal platform-constants) with correct struct layouts,
 * signal numbers, and flag values for the current OS/architecture.
 *
 * Usage:
 *   cc -o tools/gen-platform-constants tools/gen-platform-constants.c
 *   tools/gen-platform-constants > src/hafod/internal/platform-constants.ss
 */

#include <stdio.h>
#include <stddef.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <dirent.h>
#include <termios.h>
#include <time.h>
#include <sys/times.h>
#include <regex.h>
#include <glob.h>
#include <fcntl.h>
#include <pwd.h>
#include <grp.h>
#include <spawn.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/utsname.h>

#define EMIT(name, val) printf("  (define %s %d)\n", name, (int)(val))
#define EMIT_OFFSET(name, type, field) \
    printf("  (define %s %d)\n", name, (int)offsetof(type, field))
#define EMIT_SIZEOF(name, type) \
    printf("  (define %s %d)\n", name, (int)sizeof(type))
#define EMIT_FIELD_SIZEOF(name, type, field) \
    printf("  (define %s %d)\n", name, (int)sizeof(((type *)0)->field))

int main(void) {
    printf(";;; (hafod internal platform-constants) -- Auto-generated, do not edit\n");
    printf(";;; Generated by tools/gen-platform-constants.c for this platform.\n");
    printf("\n");
    printf("(library (hafod internal platform-constants)\n");
    printf("  (export\n");

    /* struct stat */
    printf("    SIZEOF-STAT\n");
    printf("    STAT-ST-DEV STAT-ST-INO STAT-ST-NLINK STAT-ST-MODE\n");
    printf("    STAT-ST-UID STAT-ST-GID STAT-ST-RDEV STAT-ST-SIZE\n");
    printf("    STAT-ST-BLKSIZE STAT-ST-BLOCKS STAT-ST-ATIM STAT-ST-MTIM STAT-ST-CTIM\n");
    printf("    SIZEOF-ST-DEV SIZEOF-ST-INO SIZEOF-ST-NLINK SIZEOF-ST-MODE\n");
    printf("    SIZEOF-ST-RDEV SIZEOF-ST-BLKSIZE SIZEOF-ST-BLOCKS\n");

    /* struct dirent */
    printf("    DIRENT-D-INO DIRENT-D-OFF DIRENT-D-RECLEN DIRENT-D-TYPE DIRENT-D-NAME\n");

    /* struct passwd */
    printf("    PW-NAME PW-PASSWD PW-UID PW-GID PW-GECOS PW-DIR PW-SHELL\n");

    /* struct group */
    printf("    GR-NAME GR-PASSWD GR-GID GR-MEM\n");

    /* struct termios */
    printf("    SIZEOF-TERMIOS\n");
    printf("    TERMIOS-C-IFLAG TERMIOS-C-OFLAG TERMIOS-C-CFLAG TERMIOS-C-LFLAG\n");
    printf("    TERMIOS-C-CC TERMIOS-C-ISPEED TERMIOS-C-OSPEED\n");

    /* struct tm */
    printf("    SIZEOF-TM\n");
    printf("    TM-SEC TM-MIN TM-HOUR TM-MDAY TM-MON TM-YEAR\n");
    printf("    TM-WDAY TM-YDAY TM-ISDST TM-GMTOFF TM-ZONE\n");

    /* struct tms */
    printf("    SIZEOF-TMS\n");

    /* regex_t and regmatch_t */
    printf("    SIZEOF-REGEX-T SIZEOF-REGMATCH-T SIZEOF-REGOFF-T\n");

    /* glob_t */
    printf("    SIZEOF-GLOB-T GLOB-GL-PATHC GLOB-GL-PATHV\n");

    /* posix_spawn_file_actions_t */
    printf("    SIZEOF-SPAWN-FA\n");

    /* Open flags */
    printf("    PLAT-O-CREAT PLAT-O-EXCL PLAT-O-TRUNC PLAT-O-APPEND PLAT-O-NONBLOCK\n");

    /* Signals that vary across platforms */
    printf("    PLAT-SIGBUS PLAT-SIGUSR1 PLAT-SIGUSR2 PLAT-SIGCHLD\n");
    printf("    PLAT-SIGCONT PLAT-SIGSTOP PLAT-SIGTSTP PLAT-SIGTTIN PLAT-SIGTTOU\n");
    printf("    PLAT-SIGURG PLAT-SIGXCPU PLAT-SIGXFSZ PLAT-SIGVTALRM\n");
    printf("    PLAT-SIGPROF PLAT-SIGWINCH PLAT-SIGIO PLAT-SIGSYS\n");

    /* TTY flag values */
    printf("    PLAT-IGNBRK PLAT-BRKINT PLAT-IGNPAR PLAT-PARMRK\n");
    printf("    PLAT-INPCK PLAT-ISTRIP PLAT-INLCR PLAT-IGNCR PLAT-ICRNL\n");
    printf("    PLAT-IXON PLAT-IXOFF PLAT-IXANY\n");
    printf("    PLAT-OPOST PLAT-ONLCR\n");
    printf("    PLAT-CSIZE PLAT-CS5 PLAT-CS6 PLAT-CS7 PLAT-CS8\n");
    printf("    PLAT-CSTOPB PLAT-CREAD PLAT-PARENB PLAT-PARODD\n");
    printf("    PLAT-HUPCL PLAT-CLOCAL\n");
    printf("    PLAT-ISIG PLAT-ICANON PLAT-ECHO PLAT-ECHOE PLAT-ECHOK\n");
    printf("    PLAT-ECHONL PLAT-NOFLSH PLAT-TOSTOP PLAT-IEXTEN\n");

    /* TTY cc indices */
    printf("    PLAT-VINTR PLAT-VQUIT PLAT-VERASE PLAT-VKILL PLAT-VEOF\n");
    printf("    PLAT-VTIME PLAT-VMIN PLAT-VSTART PLAT-VSTOP PLAT-VSUSP\n");
    printf("    PLAT-VEOL PLAT-VREPRINT PLAT-VDISCARD PLAT-VWERASE PLAT-VLNEXT PLAT-VEOL2\n");
    printf("    PLAT-NCCS\n");

    /* termios actions */
    printf("    PLAT-TCSANOW PLAT-TCSADRAIN PLAT-TCSAFLUSH\n");
    printf("    PLAT-TCIFLUSH PLAT-TCOFLUSH PLAT-TCIOFLUSH\n");
    printf("    PLAT-TCOOFF PLAT-TCOON PLAT-TCIOFF PLAT-TCION\n");

    /* fcntl */
    printf("    PLAT-F-GETFD PLAT-F-SETFD PLAT-FD-CLOEXEC PLAT-F-GETFL PLAT-F-SETFL\n");

    /* ioctl */
    printf("    PLAT-TIOCSCTTY\n");

    /* utsname */
    printf("    PLAT-UTSNAME-FIELD-LEN\n");

    /* FNM flags */
    printf("    PLAT-FNM-NOESCAPE PLAT-FNM-PATHNAME PLAT-FNM-PERIOD\n");

    /* Regex flags */
    printf("    PLAT-REG-EXTENDED PLAT-REG-ICASE PLAT-REG-NOSUB PLAT-REG-NEWLINE\n");
    printf("    PLAT-REG-NOTBOL PLAT-REG-NOTEOL PLAT-REG-NOMATCH\n");

    printf("  )\n");
    printf("  (import (chezscheme))\n\n");

    /* ============================================================ */
    printf("  ;; struct stat\n");
    EMIT_SIZEOF("SIZEOF-STAT", struct stat);
    EMIT_OFFSET("STAT-ST-DEV", struct stat, st_dev);
    EMIT_OFFSET("STAT-ST-INO", struct stat, st_ino);
    EMIT_OFFSET("STAT-ST-NLINK", struct stat, st_nlink);
    EMIT_OFFSET("STAT-ST-MODE", struct stat, st_mode);
    EMIT_OFFSET("STAT-ST-UID", struct stat, st_uid);
    EMIT_OFFSET("STAT-ST-GID", struct stat, st_gid);
    EMIT_OFFSET("STAT-ST-RDEV", struct stat, st_rdev);
    EMIT_OFFSET("STAT-ST-SIZE", struct stat, st_size);
    EMIT_OFFSET("STAT-ST-BLKSIZE", struct stat, st_blksize);
    EMIT_OFFSET("STAT-ST-BLOCKS", struct stat, st_blocks);
    /* st_atim is a struct timespec; macOS uses st_atimespec instead */
#ifdef __APPLE__
    EMIT_OFFSET("STAT-ST-ATIM", struct stat, st_atimespec);
    EMIT_OFFSET("STAT-ST-MTIM", struct stat, st_mtimespec);
    EMIT_OFFSET("STAT-ST-CTIM", struct stat, st_ctimespec);
#else
    EMIT_OFFSET("STAT-ST-ATIM", struct stat, st_atim);
    EMIT_OFFSET("STAT-ST-MTIM", struct stat, st_mtim);
    EMIT_OFFSET("STAT-ST-CTIM", struct stat, st_ctim);
#endif
    EMIT_FIELD_SIZEOF("SIZEOF-ST-DEV", struct stat, st_dev);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-INO", struct stat, st_ino);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-NLINK", struct stat, st_nlink);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-MODE", struct stat, st_mode);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-RDEV", struct stat, st_rdev);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-BLKSIZE", struct stat, st_blksize);
    EMIT_FIELD_SIZEOF("SIZEOF-ST-BLOCKS", struct stat, st_blocks);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct dirent\n");
    EMIT_OFFSET("DIRENT-D-INO", struct dirent, d_ino);
#ifdef __linux__
    EMIT_OFFSET("DIRENT-D-OFF", struct dirent, d_off);
#else
    /* macOS/BSD don't have d_off in struct dirent */
    EMIT("DIRENT-D-OFF", -1);
#endif
    EMIT_OFFSET("DIRENT-D-RECLEN", struct dirent, d_reclen);
    EMIT_OFFSET("DIRENT-D-TYPE", struct dirent, d_type);
    EMIT_OFFSET("DIRENT-D-NAME", struct dirent, d_name);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct passwd\n");
    EMIT_OFFSET("PW-NAME", struct passwd, pw_name);
    EMIT_OFFSET("PW-PASSWD", struct passwd, pw_passwd);
    EMIT_OFFSET("PW-UID", struct passwd, pw_uid);
    EMIT_OFFSET("PW-GID", struct passwd, pw_gid);
    EMIT_OFFSET("PW-GECOS", struct passwd, pw_gecos);
    EMIT_OFFSET("PW-DIR", struct passwd, pw_dir);
    EMIT_OFFSET("PW-SHELL", struct passwd, pw_shell);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct group\n");
    EMIT_OFFSET("GR-NAME", struct group, gr_name);
    EMIT_OFFSET("GR-PASSWD", struct group, gr_passwd);
    EMIT_OFFSET("GR-GID", struct group, gr_gid);
    EMIT_OFFSET("GR-MEM", struct group, gr_mem);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct termios\n");
    EMIT_SIZEOF("SIZEOF-TERMIOS", struct termios);
    EMIT_OFFSET("TERMIOS-C-IFLAG", struct termios, c_iflag);
    EMIT_OFFSET("TERMIOS-C-OFLAG", struct termios, c_oflag);
    EMIT_OFFSET("TERMIOS-C-CFLAG", struct termios, c_cflag);
    EMIT_OFFSET("TERMIOS-C-LFLAG", struct termios, c_lflag);
    EMIT_OFFSET("TERMIOS-C-CC", struct termios, c_cc);
    EMIT_OFFSET("TERMIOS-C-ISPEED", struct termios, c_ispeed);
    EMIT_OFFSET("TERMIOS-C-OSPEED", struct termios, c_ospeed);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct tm\n");
    EMIT_SIZEOF("SIZEOF-TM", struct tm);
    EMIT_OFFSET("TM-SEC", struct tm, tm_sec);
    EMIT_OFFSET("TM-MIN", struct tm, tm_min);
    EMIT_OFFSET("TM-HOUR", struct tm, tm_hour);
    EMIT_OFFSET("TM-MDAY", struct tm, tm_mday);
    EMIT_OFFSET("TM-MON", struct tm, tm_mon);
    EMIT_OFFSET("TM-YEAR", struct tm, tm_year);
    EMIT_OFFSET("TM-WDAY", struct tm, tm_wday);
    EMIT_OFFSET("TM-YDAY", struct tm, tm_yday);
    EMIT_OFFSET("TM-ISDST", struct tm, tm_isdst);
    EMIT_OFFSET("TM-GMTOFF", struct tm, tm_gmtoff);
    EMIT_OFFSET("TM-ZONE", struct tm, tm_zone);
    printf("\n");

    /* ============================================================ */
    printf("  ;; struct tms\n");
    EMIT_SIZEOF("SIZEOF-TMS", struct tms);
    printf("\n");

    /* ============================================================ */
    printf("  ;; regex_t and regmatch_t\n");
    EMIT_SIZEOF("SIZEOF-REGEX-T", regex_t);
    EMIT_SIZEOF("SIZEOF-REGMATCH-T", regmatch_t);
    EMIT_SIZEOF("SIZEOF-REGOFF-T", regoff_t);
    printf("\n");

    /* ============================================================ */
    printf("  ;; glob_t\n");
    EMIT_SIZEOF("SIZEOF-GLOB-T", glob_t);
    EMIT_OFFSET("GLOB-GL-PATHC", glob_t, gl_pathc);
    EMIT_OFFSET("GLOB-GL-PATHV", glob_t, gl_pathv);
    printf("\n");

    /* ============================================================ */
    printf("  ;; posix_spawn_file_actions_t\n");
    EMIT_SIZEOF("SIZEOF-SPAWN-FA", posix_spawn_file_actions_t);
    printf("\n");

    /* ============================================================ */
    printf("  ;; Open flags\n");
    EMIT("PLAT-O-CREAT", O_CREAT);
    EMIT("PLAT-O-EXCL", O_EXCL);
    EMIT("PLAT-O-TRUNC", O_TRUNC);
    EMIT("PLAT-O-APPEND", O_APPEND);
    EMIT("PLAT-O-NONBLOCK", O_NONBLOCK);
    printf("\n");

    /* ============================================================ */
    printf("  ;; Signal constants\n");
    EMIT("PLAT-SIGBUS", SIGBUS);
    EMIT("PLAT-SIGUSR1", SIGUSR1);
    EMIT("PLAT-SIGUSR2", SIGUSR2);
    EMIT("PLAT-SIGCHLD", SIGCHLD);
    EMIT("PLAT-SIGCONT", SIGCONT);
    EMIT("PLAT-SIGSTOP", SIGSTOP);
    EMIT("PLAT-SIGTSTP", SIGTSTP);
    EMIT("PLAT-SIGTTIN", SIGTTIN);
    EMIT("PLAT-SIGTTOU", SIGTTOU);
    EMIT("PLAT-SIGURG", SIGURG);
    EMIT("PLAT-SIGXCPU", SIGXCPU);
    EMIT("PLAT-SIGXFSZ", SIGXFSZ);
    EMIT("PLAT-SIGVTALRM", SIGVTALRM);
    EMIT("PLAT-SIGPROF", SIGPROF);
    EMIT("PLAT-SIGWINCH", SIGWINCH);
    EMIT("PLAT-SIGIO", SIGIO);
    EMIT("PLAT-SIGSYS", SIGSYS);
    printf("\n");

    /* ============================================================ */
    printf("  ;; TTY input flags\n");
    EMIT("PLAT-IGNBRK", IGNBRK);
    EMIT("PLAT-BRKINT", BRKINT);
    EMIT("PLAT-IGNPAR", IGNPAR);
    EMIT("PLAT-PARMRK", PARMRK);
    EMIT("PLAT-INPCK", INPCK);
    EMIT("PLAT-ISTRIP", ISTRIP);
    EMIT("PLAT-INLCR", INLCR);
    EMIT("PLAT-IGNCR", IGNCR);
    EMIT("PLAT-ICRNL", ICRNL);
    EMIT("PLAT-IXON", IXON);
    EMIT("PLAT-IXOFF", IXOFF);
    EMIT("PLAT-IXANY", IXANY);
    printf("\n");

    printf("  ;; TTY output flags\n");
    EMIT("PLAT-OPOST", OPOST);
    EMIT("PLAT-ONLCR", ONLCR);
    printf("\n");

    printf("  ;; TTY control flags\n");
    EMIT("PLAT-CSIZE", CSIZE);
    EMIT("PLAT-CS5", CS5);
    EMIT("PLAT-CS6", CS6);
    EMIT("PLAT-CS7", CS7);
    EMIT("PLAT-CS8", CS8);
    EMIT("PLAT-CSTOPB", CSTOPB);
    EMIT("PLAT-CREAD", CREAD);
    EMIT("PLAT-PARENB", PARENB);
    EMIT("PLAT-PARODD", PARODD);
    EMIT("PLAT-HUPCL", HUPCL);
    EMIT("PLAT-CLOCAL", CLOCAL);
    printf("\n");

    printf("  ;; TTY local flags\n");
    EMIT("PLAT-ISIG", ISIG);
    EMIT("PLAT-ICANON", ICANON);
    EMIT("PLAT-ECHO", ECHO);
    EMIT("PLAT-ECHOE", ECHOE);
    EMIT("PLAT-ECHOK", ECHOK);
    EMIT("PLAT-ECHONL", ECHONL);
    EMIT("PLAT-NOFLSH", NOFLSH);
    EMIT("PLAT-TOSTOP", TOSTOP);
    EMIT("PLAT-IEXTEN", IEXTEN);
    printf("\n");

    printf("  ;; TTY cc indices\n");
    EMIT("PLAT-VINTR", VINTR);
    EMIT("PLAT-VQUIT", VQUIT);
    EMIT("PLAT-VERASE", VERASE);
    EMIT("PLAT-VKILL", VKILL);
    EMIT("PLAT-VEOF", VEOF);
    EMIT("PLAT-VTIME", VTIME);
    EMIT("PLAT-VMIN", VMIN);
    EMIT("PLAT-VSTART", VSTART);
    EMIT("PLAT-VSTOP", VSTOP);
    EMIT("PLAT-VSUSP", VSUSP);
    EMIT("PLAT-VEOL", VEOL);
    EMIT("PLAT-VREPRINT", VREPRINT);
    EMIT("PLAT-VDISCARD", VDISCARD);
    EMIT("PLAT-VWERASE", VWERASE);
    EMIT("PLAT-VLNEXT", VLNEXT);
    EMIT("PLAT-VEOL2", VEOL2);
    EMIT("PLAT-NCCS", NCCS);
    printf("\n");

    printf("  ;; termios actions\n");
    EMIT("PLAT-TCSANOW", TCSANOW);
    EMIT("PLAT-TCSADRAIN", TCSADRAIN);
    EMIT("PLAT-TCSAFLUSH", TCSAFLUSH);
    EMIT("PLAT-TCIFLUSH", TCIFLUSH);
    EMIT("PLAT-TCOFLUSH", TCOFLUSH);
    EMIT("PLAT-TCIOFLUSH", TCIOFLUSH);
    EMIT("PLAT-TCOOFF", TCOOFF);
    EMIT("PLAT-TCOON", TCOON);
    EMIT("PLAT-TCIOFF", TCIOFF);
    EMIT("PLAT-TCION", TCION);
    printf("\n");

    printf("  ;; fcntl\n");
    EMIT("PLAT-F-GETFD", F_GETFD);
    EMIT("PLAT-F-SETFD", F_SETFD);
    EMIT("PLAT-FD-CLOEXEC", FD_CLOEXEC);
    EMIT("PLAT-F-GETFL", F_GETFL);
    EMIT("PLAT-F-SETFL", F_SETFL);
    printf("\n");

    printf("  ;; ioctl\n");
    EMIT("PLAT-TIOCSCTTY", TIOCSCTTY);
    printf("\n");

    printf("  ;; utsname\n");
    {
        struct utsname u;
        EMIT("PLAT-UTSNAME-FIELD-LEN", sizeof(u.sysname));
    }
    printf("\n");

    printf("  ;; fnmatch flags\n");
    EMIT("PLAT-FNM-NOESCAPE", 1);  /* FNM_NOESCAPE is 1 on both Linux and macOS */
    EMIT("PLAT-FNM-PATHNAME", 2);  /* FNM_PATHNAME is 2 on both */
    EMIT("PLAT-FNM-PERIOD", 4);    /* FNM_PERIOD is 4 on both */
    printf("\n");

    printf("  ;; Regex flags\n");
    EMIT("PLAT-REG-EXTENDED", REG_EXTENDED);
    EMIT("PLAT-REG-ICASE", REG_ICASE);
    EMIT("PLAT-REG-NOSUB", REG_NOSUB);
    EMIT("PLAT-REG-NEWLINE", REG_NEWLINE);
    EMIT("PLAT-REG-NOTBOL", REG_NOTBOL);
    EMIT("PLAT-REG-NOTEOL", REG_NOTEOL);
    EMIT("PLAT-REG-NOMATCH", REG_NOMATCH);

    printf("\n) ; end library\n");
    return 0;
}
