/* hafod-standalone.c -- Self-contained hafod binary
 *
 * Embeds LZ4-compressed vfasl boot files (petite + hafod) and the
 * launcher program.  Decompresses boot files at startup, then loads
 * them from memory.  No external files needed at runtime.
 *
 * Compressed format: 8-byte big-endian tagged fixnum ((size << 3) | 1),
 * then raw LZ4 data.  (Matches Chez Scheme's bytevector-compress output.)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <lz4.h>
#include <scheme.h>

/* Non-variadic wrappers for variadic POSIX functions.
 * Required on ARM64 macOS where variadic args use a different ABI. */
int hafod_open3(const char *path, int flags, int mode) { return open(path, flags, mode); }
int hafod_fcntl_int(int fd, int cmd, int arg) { return fcntl(fd, cmd, arg); }
int hafod_fcntl_void(int fd, int cmd) { return fcntl(fd, cmd); }
int hafod_ioctl_int(int fd, unsigned long req, int arg) { return ioctl(fd, req, arg); }
int hafod_ioctl_ptr(int fd, unsigned long req, void *arg) { return ioctl(fd, req, arg); }

/* Generated by build-standalone.ss — LZ4 compressed vfasl boot files.
 * Each blob is: [8-byte BE tagged fixnum] [LZ4 compressed data] */
extern const unsigned char petite_boot_cmp[];
extern const unsigned int petite_boot_cmp_size;
extern const unsigned char hafod_boot_cmp[];
extern const unsigned int hafod_boot_cmp_size;
extern const unsigned char hafod_program[];
extern const unsigned int hafod_program_size;

/* Write the program .so to a temporary file and return its path.
 * On Linux 3.17+ we use memfd_create for an anonymous in-memory file.
 * On other platforms we fall back to a regular temp file (unlinked
 * immediately so it is cleaned up even if we crash). */
static int write_program_to_file(char *path, size_t pathsz) {
#ifdef __linux__
    /* memfd_create is available since glibc 2.27 / Linux 3.17 */
#  include <sys/syscall.h>
    int fd = syscall(SYS_memfd_create, "hafod.so", 0u);
    if (fd >= 0) {
        if (write(fd, hafod_program, hafod_program_size) == (ssize_t)hafod_program_size) {
            lseek(fd, 0, SEEK_SET);
            snprintf(path, pathsz, "/proc/self/fd/%d", fd);
            return fd;
        }
        close(fd);
    }
#endif
    /* Portable fallback: write to a temp file, unlink immediately */
    snprintf(path, pathsz, "/tmp/hafod-prog-XXXXXX");
    int fd2 = mkstemp(path);
    if (fd2 < 0) return -1;
    if (write(fd2, hafod_program, hafod_program_size) != (ssize_t)hafod_program_size) {
        close(fd2);
        unlink(path);
        return -1;
    }
    lseek(fd2, 0, SEEK_SET);
    /* Unlink so the file is removed when fd is closed */
    unlink(path);
    /* Re-read path via /dev/fd if possible (macOS/BSD) */
#ifndef __linux__
    snprintf(path, pathsz, "/dev/fd/%d", fd2);
#endif
    return fd2;
}

/* Decompress a Chez bytevector-compress blob.
 * Header: 8-byte big-endian tagged fixnum = (orig_size << 3) | 1 */
static void *decompress(const unsigned char *src, unsigned int src_size,
                        unsigned int *out_size) {
    unsigned long long tag = 0;
    for (int i = 0; i < 8; i++)
        tag = (tag << 8) | src[i];
    *out_size = (unsigned int)(tag >> 3);

    void *dst = malloc(*out_size);
    if (!dst) return NULL;

    int ret = LZ4_decompress_safe((const char *)(src + 8), dst,
                                  src_size - 8, *out_size);
    if (ret < 0) { free(dst); return NULL; }
    return dst;
}

static void custom_init(void) { }

int main(int argc, const char **argv) {
    unsigned int petite_size, hafod_size;
    void *petite = decompress(petite_boot_cmp, petite_boot_cmp_size, &petite_size);
    void *hafod = decompress(hafod_boot_cmp, hafod_boot_cmp_size, &hafod_size);
    if (!petite || !hafod) {
        fprintf(stderr, "hafod: boot decompression failed\n");
        return 1;
    }

    Sscheme_init(0);
    Sregister_boot_file_bytes("petite", petite, (iptr)petite_size);
    Sregister_boot_file_bytes("hafod", hafod, (iptr)hafod_size);
    Sbuild_heap(0, custom_init);
    free(petite);
    free(hafod);

    /* Write the launcher program to a file descriptor */
    char progpath[256];
    int progfd = write_program_to_file(progpath, sizeof(progpath));
    if (progfd < 0) { perror("hafod: program temp file"); return 1; }

    int ret = Sscheme_program(progpath, argc, argv);
    Sscheme_deinit();
    close(progfd);
    return ret;
}
